const transportOptions = ["AG/GA", "Half Price", "Car", "None"];
const residencies = [
    "76FM",
    "700 Clauses",
    "Anywhere out of the Globe",
    "Break Age",
    "Die Schnittstelle",
    "Diggy digg aka the story of no style",
    "Distantes résonances",
    "exzenter",
    "Free Internet Free People",
    "Gradients",
    "High Levels!",
    "Ida Leto's walk",
    "Le Buvard Bavard",
    "Le Four",
    "Patate Douce Experience",
    "Rescue",
    "Statement",
    "Talk with Madeleines",
    "Teinture Mère",
    "Ultime Seum",
    "Utopia Electrónica",
    "Uña &amp; Mugre",
]
const tags = [
    "ambient",
    "bass",
    "breakbeat",
    "club",
    "deconstructed",
    "dnb",
    "ebm",
    "ecology",
    "electro",
    "electronic",
    "electronica",
    "experimental",
    "funk",
    "global",
    "hardcore",
    "hip-hop",
    "house",
    "hybrid",
    "italo",
    "jungle",
    "knowledge",
    "latinx",
    "machines",
    "minimal",
    "rap",
    "rave",
    "selectors",
    "synth",
    "talks",
    "techno",
    "traditional",
    "trance",
    "variable",
].sort();

export {
    transportOptions,
    tags,
    residencies,
}